check_task:
  # This implementation is temporary, until a shell checking image is ready
  container:
    image: greyltc/archlinux:latest
  setup_script:
    - pacman -Syyu --noconfirm
    - pacman -S --noconfirm make shellcheck shfmt
    - curl -SfL https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 -o /usr/local/bin/hadolint
    - chmod 0755 /usr/local/bin/hadolint
  check_script: make check

docker_builder:
  only_if: $CIRRUS_TAG != ''
  depends_on:
    - check
  env:
    IMAGE_NAME: fnichol/vint
    DOCKER_USERNAME: ENCRYPTED[87502d3f2acc6ef65aadfa9a276866c48236bda445c531c1875571029cb30c01562e6bb739f9466fee74164d71dcde5e]
    DOCKER_PASSWORD: ENCRYPTED[de7ac9dd97e8261d022a1fe0288ef9b5504099b59e75de2be57a19d29201c562060a888db924e2b852695ee4e64006b3]
  build_script: ./build.sh "$IMAGE_NAME" "$CIRRUS_TAG" latest
  login_script: >
    echo "$DOCKER_PASSWORD" \
      | docker login --username "$DOCKER_USERNAME" --password-stdin
  push_script: docker push "$IMAGE_NAME:$CIRRUS_TAG"
