check_task:
  # This implementation is temporary, until a shell checking image is ready
  container:
    image: greyltc/archlinux:latest
  setup_script:
    - pacman -Syy --noconfirm
    - pacman -S --noconfirm shellcheck shfmt
    - curl -SfL https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 -o /usr/local/bin/hadolint
    - chmod 0755 /usr/local/bin/hadolint
  check_script: make check

docker_builder:
  only_if: $CIRRUS_TAG != ''
  depends_on:
    - check
  env:
    IMAGE_NAME: fnichol/vint
    DOCKER_USERNAME: user
    DOCKER_PASSWORD: pass
  build_script: ./build.sh "$IMAGE_NAME" "$CIRRUS_TAG" latest
  login_script: >
    cat "$DOCKER_PASSWORD"
      | docker login --username "$DOCKER_USERNAME" --password-stdin
  push_script: docker push "$IMAGE_NAME:$CIRRUS_TAG"
